# Generated by Django 2.2.4 on 2019-08-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', 'data_migration_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True, db_column='url', help_text='URL for term description', verbose_name='term url'),
        ),
    ]
