# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-12 04:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(db_column=b'annotation_type', help_text='Type of annotation', max_length=30, verbose_name='annotation type')),
                ('event_type', models.CharField(db_column=b'event_type', help_text='Type of event being annotated', max_length=30, verbose_name='event type')),
                ('label', django.contrib.postgres.fields.hstore.HStoreField(db_column=b'label', help_text='Labels associated to annotation', verbose_name='label')),
                ('annotation', django.contrib.postgres.fields.jsonb.JSONField(db_column=b'annotation', help_text='Information of annotation location within item', verbose_name='annotation')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(db_column=b'metadata', help_text='Metadata associated to annotation', verbose_name='metadata')),
                ('certainty', models.FloatField(blank=True, db_column=b'certainty', help_text='Level of certainty of location or labelling of annotation', null=True, verbose_name='certainty')),
                ('quality', models.CharField(blank=True, choices=[(b'L', b'baja'), (b'M', b'media'), (b'H', b'alta')], db_column=b'quality', help_text='Quality of item content inside annotation', max_length=10, verbose_name='quality')),
                ('commentaries', models.TextField(blank=True, db_column=b'commentaries', help_text='Commentaries of annotator', verbose_name='commentaries')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column=b'created_on', help_text='Date of creation of annotation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column=b'modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('created_by', models.ForeignKey(blank=True, db_column=b'created_by', help_text='Creator of annotation (User)', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'name', help_text='Name of collection', max_length=70, verbose_name='name')),
                ('description', models.TextField(db_column=b'description', help_text='Description of collection', verbose_name='description')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(db_column=b'metadata', help_text='Collection metadata', verbose_name='metadata')),
                ('coordinator', models.ForeignKey(blank=True, db_column=b'coordinator_id', help_text='Collection coordinator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='coordinator id')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(db_column=b'collection_id', help_text='Collection beign owned', on_delete=django.db.models.deletion.CASCADE, to='database.Collection', verbose_name='collection id')),
                ('user', models.ForeignKey(db_column=b'user_id', help_text='User owner of collection', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('configurations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('bundle', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=70)),
                ('filesize', models.IntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('hash_function', models.CharField(choices=[(b'md5', b'md5'), (b'sha244', b'sha244'), (b'sha256', b'sha256'), (b'sha384', b'sha384'), (b'sha512', b'sha512')], max_length=10)),
                ('type', models.CharField(max_length=40)),
                ('source_foreign_key', models.CharField(blank=True, max_length=50)),
                ('media_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('captured_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('document', models.CharField(blank=True, max_length=70)),
                ('created_on', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField()),
                ('commentaries', models.TextField(blank=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Device')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=70)),
                ('hash', models.CharField(max_length=64)),
                ('hash_function', models.CharField(choices=[(b'md5', b'md5'), (b'sha244', b'sha244'), (b'sha256', b'sha256'), (b'sha384', b'sha384'), (b'sha512', b'sha512')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=40)),
                ('media_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('geo_ref', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=64)),
                ('source_file', models.CharField(max_length=64)),
                ('parse_function', models.CharField(max_length=50)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[(b'admin', b'admin'), (b'developer', b'developer'), (b'curator', b'curator'), (b'user', b'user')], max_length=30)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='synonym',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_source', to='database.Term'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_target', to='database.Term'),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Site'),
        ),
        migrations.AddField(
            model_name='item',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Licence'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='sampling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.SamplingEvent'),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Source'),
        ),
        migrations.AddField(
            model_name='entailment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entailment_source', to='database.Term'),
        ),
        migrations.AddField(
            model_name='entailment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entailment_target', to='database.Term'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='item',
            field=models.ForeignKey(db_column=b'item_id', help_text='Annotated item', on_delete=django.db.models.deletion.PROTECT, to='database.Item', verbose_name='item id'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='model',
            field=models.ForeignKey(db_column=b'model_id', help_text='Creator of annotation (AI model)', on_delete=django.db.models.deletion.CASCADE, to='database.Model', verbose_name='model id'),
        ),
    ]
