# Generated by Django 2.1.7 on 2019-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='document',
            field=models.FileField(blank=True, db_column='document', help_text='Legal document of licence agreement', upload_to='documents/licences/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='licencetype',
            name='document_template',
            field=models.FileField(blank=True, db_column='document_template', help_text='Template for licence document', unique=True, upload_to='documents/licence_types/', verbose_name='document template'),
        ),
    ]
