# Generated by Django 2.1.7 on 2019-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaldevice',
            name='serial_number',
            field=models.CharField(blank=True, db_column='serial_number', help_text='Serial number of device', max_length=128, null=True, verbose_name='serial number'),
        ),
        migrations.AlterUniqueTogether(
            name='physicaldevice',
            unique_together={('serial_number', 'device')},
        ),
    ]
