# Generated by Django 2.1.7 on 2019-03-18 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtool',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotationtool',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='collectiontype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiontype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='devicebrand',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicebrand',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='entailment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entailment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='entailmenttype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entailmenttype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='institution',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='licencetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licencetype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='metacollection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metacollection',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='physicaldevice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicaldevice',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='samplingeventtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingeventtype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='secondaryitem',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitetype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synonym',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='term',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AddField(
            model_name='termtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now, help_text='Date of entry creation', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termtype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of entry creation', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='secondaryitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of entry creation', verbose_name='created on'),
        ),
    ]
