# Generated by Django 2.1.7 on 2019-03-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ready_event_types',
            field=models.ManyToManyField(blank=True, help_text='Types of event for which item has been fully annotated', to='database.EventType', verbose_name='ready event types'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(db_column='site_type', default='generic site', help_text='Type of site', on_delete=django.db.models.deletion.PROTECT, to='database.SiteType', verbose_name='site type'),
        ),
    ]
