# Generated by Django 2.2.4 on 2019-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_term_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='mime_types',
            field=models.ManyToManyField(blank=True, db_column='mime_types', help_text='Possible mime types for files generated by devicesof this type', to='database.MimeType', verbose_name='mime types'),
        ),
    ]
