# Generated by Django 2.1.7 on 2019-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='is_active', default=False, editable=False, help_text='Licence is still active', verbose_name='is active'),
        ),
    ]
