# Generated by Django 2.1.7 on 2019-06-06 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='licence',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='creator_id', help_text='Creator of object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='licence',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', editable=False, help_text='User who made modifications last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='licence',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on'),
        ),
    ]
