# Generated by Django 2.1.7 on 2019-03-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190328_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionsite',
            name='metadata',
        ),
    ]
