# Generated by Django 2.1.7 on 2019-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190313_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='document_template',
            field=models.FileField(blank=True, db_column='document_template', help_text='Template for licence document', null=True, unique=True, upload_to='documents/licence_types/', verbose_name='document template'),
        ),
    ]
