# Generated by Django 2.1.7 on 2019-03-16 01:31

import database.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190314_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role Type', 'verbose_name_plural': 'Role Types'},
        ),
        migrations.AddField(
            model_name='collectiontype',
            name='logo',
            field=models.ImageField(blank=True, db_column='logo', help_text='Logo of collection type', null=True, upload_to='images/collection_types/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(db_column='site_type', default='sitio genérico', help_text='Type of site', on_delete=django.db.models.deletion.PROTECT, to='database.SiteType', verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='source',
            field=models.ForeignKey(db_column='source_id', help_text='Reference to the source of synonym', on_delete=django.db.models.deletion.CASCADE, related_name='synonym_source', to='database.Term', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='target',
            field=models.ForeignKey(db_column='target_id', help_text='Reference to the target of the synonym', on_delete=django.db.models.deletion.CASCADE, related_name='synonym_target', to='database.Term', verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='term',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='metadata', default=database.utils.empty_JSON, help_text='Metadata associated to term', null=True, verbose_name='metadata'),
        ),
    ]
