# Generated by Django 2.1.7 on 2019-03-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_collectionsite_metadata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectiondevice',
            unique_together={('device', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='collectiondevicetype',
            unique_together={('collection_type', 'device_type')},
        ),
        migrations.AlterUniqueTogether(
            name='collectionitemtype',
            unique_together={('collection_type', 'item_type')},
        ),
        migrations.AlterUniqueTogether(
            name='collectionrole',
            unique_together={('collection_type', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='collectionuser',
            unique_together={('collection', 'user')},
        ),
    ]
