# Generated by Django 2.1.7 on 2019-03-31 23:28

import database.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190331_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='annotation', default=database.utils.empty_JSON, help_text='Information of annotation location within item', verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='annotation_configuration', default=database.utils.empty_JSON, help_text='Configuration of annotation tool', verbose_name='annotation configuration'),
        ),
    ]
