# Generated by Django 2.1.7 on 2019-04-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190331_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryitem',
            name='hash_function',
        ),
    ]
