# Generated by Django 2.2.4 on 2019-09-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190908_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_on'], 'permissions': (('add_collection_site', 'Can add site to collection'), ('add_collection_item', 'Can add item to collection'), ('add_collection_device', 'Can add device to collection'), ('add_collection_sampling_event', 'Can add a sampling event to collection'), ('add_collection_user', 'Can add user to collection'), ('add_collection_licence', 'Can add licence to collection'), ('add_collection_annotation', 'Can annotate items in collection'), ('add_collection_annotation_vote', 'Can vote on annotations of items in collection'), ('view_collection_sites', 'Can view sites in collection'), ('view_collection_items', 'Can view items in collection'), ('view_collection_devices', 'Can view devices in collection'), ('view_collection_sampling_events', 'Can view sampling event in collection'), ('view_collection_annotations', 'Can view annotations of items in collection'), ('change_collection_sites', 'Can change sites in collection'), ('change_collection_users', 'Can change user info in collection'), ('change_collection_items', 'Can change items in collection'), ('change_collection_devices', 'Can change devices in collection'), ('change_collection_annotations', 'Can change annotations of items in collection'), ('change_collection_sampling_events', 'Can change sampling events in collection'), ('download_collection_items', 'Can download annotation items')), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
