# Generated by Django 2.1.7 on 2019-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_secondaryitem_hash_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='filesize',
            field=models.IntegerField(blank=True, db_column='filesize', help_text='Size of resource in Bytes', null=True, verbose_name='file size'),
        ),
    ]
