# Generated by Django 2.1.7 on 2019-04-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190401_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='creator',
            new_name='created_by',
        ),
    ]
