# Generated by Django 2.2.5 on 2019-10-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_locality_localitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitytype',
            name='publication_date',
            field=models.DateField(blank=True, db_column='publication_date', default=None, help_text='Date of publication of localities defined in this type', verbose_name='publication date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localitytype',
            name='original_datum',
            field=models.TextField(blank=True, db_column='original_datum', help_text='Datum used for the original coordinates for localities of this type in WTK format', verbose_name='original datum'),
        ),
        migrations.AlterField(
            model_name='localitytype',
            name='source',
            field=models.URLField(blank=True, db_column='source', help_text='Source of information for localities of this type', max_length=128, verbose_name='source'),
        ),
    ]
