# Generated by Django 2.2.5 on 2019-10-22 04:53

import database.models.items.items
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20191021_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, db_column='item_thumbnail', help_text='Thumbnail associated to file', null=True, upload_to=database.models.items.items.get_thumbnail_path, verbose_name='item thumbnail'),
        ),
    ]
