# Generated by Django 2.1.7 on 2019-02-24 02:16

from django.db import migrations


def create_basic_json_schema(apps, schema_editor):
    free_schema = {
      "definitions": {},
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "title": "Free JSON Schema"
    }

    Schema = apps.get_model('database', 'Schema')
    Schema.objects.get_or_create(
        field='global',
        name='free',
        description='JSON Schema with no restrictions',
        schema=free_schema)


def create_basic_item_types(apps, schema_editor):
    from database.conf.item_types import types

    Schema = apps.get_model('database', 'Schema')
    ItemType = apps.get_model('database', 'ItemType')

    for item_type in types:
        name = item_type['name']
        description = item_type['description']
        schema = item_type['schema']

        schema, _ = Schema.objects.get_or_create(
            field='item_media_info',
            name='{} media info'.format(name),
            description=schema.get('description', ''),
            schema=schema)

        ItemType.objects.get_or_create(
            name=name,
            description=description,
            media_info_schema=schema)


def create_basic_roles(apps, schema_editor):
    from database.conf.role_types import types

    RoleType = apps.get_model('database', 'RoleType')
    Permission = apps.get_model('auth', 'Permission')

    for role_type in types:
        group, _ = RoleType.objects.get_or_create(
            name=role_type['name'],
            description=role_type['description'])

        for permission_code in role_type['permissions']:
            try:
                permission = Permission.objects.get(codename=permission_code)
            except:
                raise Exception(permission_code)
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_basic_json_schema),
        migrations.RunPython(create_basic_item_types),
        migrations.RunPython(create_basic_roles),
    ]
